asmlink.o: asmlink.S asmlink.h
boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt.h keyboard.h rtc.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h debug.h tests.h \
  idt.h i8259.h keyboard.h rtc.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h
lib.o: lib.c lib.h types.h i8259.h
paging.o: paging.c
rtc.o: rtc.c rtc.h lib.h types.h
sys.o: sys.c sys.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
